/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package simpleapp;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import static java.util.Calendar.HOUR;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SimpleAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form SimpleAppFrame
     */
    ArrayList<String> comp = new ArrayList<>();
    ArrayList<String> dest = new ArrayList<>();

    
    public SimpleAppFrame() {
        initComponents();
        Timer t = new Timer();
        Thread th = new Thread(t);
        th.start();
        
        setSize(400, 400);
    
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        simpleAppLabel = new javax.swing.JLabel();
        itemLabel = new javax.swing.JLabel();
        itemTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sourceList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        destinationList = new javax.swing.JList();
        moveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpleapp/cer 003.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        simpleAppLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpleAppLabel.setForeground(java.awt.Color.blue);
        simpleAppLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simpleAppLabel.setText("SIMPLE APP");
        jPanel1.add(simpleAppLabel);
        simpleAppLabel.setBounds(88, 11, 183, 26);

        itemLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemLabel.setForeground(new java.awt.Color(204, 51, 255));
        itemLabel.setText("Enter An Item");
        jPanel1.add(itemLabel);
        itemLabel.setBounds(20, 63, 88, 14);

        itemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(itemTextField);
        itemTextField.setBounds(112, 60, 121, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.magenta);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Source Items");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 103, 93, 14);

        jScrollPane1.setViewportView(sourceList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 123, 122, 130);

        jScrollPane2.setViewportView(destinationList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(240, 123, 122, 130);

        moveButton.setText(">>>");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(moveButton);
        moveButton.setBounds(160, 163, 57, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.magenta);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Destination Items");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 103, 128, 14);

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        timeLabel.setForeground(java.awt.Color.magenta);
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeLabel.setText("TIMER");
        jPanel1.add(timeLabel);
        timeLabel.setBounds(277, 26, 91, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpleapp/cer 003.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
       String value = (String) sourceList.getSelectedValue();
        
       
        dest.add(value);
        destinationList.setListData(dest.toArray());
        
        comp.remove(value);
        sourceList.setListData(comp.toArray());
    }//GEN-LAST:event_moveButtonActionPerformed

    private void itemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTextFieldActionPerformed
        // TODO add your handling code here:
       String it = itemTextField.getText();
       it = it.toUpperCase();
       
       if(!comp.contains(it))
       { 
           comp.add(it);
       
           Object smt[] = comp.toArray();
           sourceList.setListData(smt);
           itemTextField.setText("");
       }
       else
       {
             JOptionPane.showMessageDialog(rootPane, "ITEM ALREADY EXIST!!");
       }
    }//GEN-LAST:event_itemTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SimpleAppFrame().setVisible(true);
            }
        });
    }
    private class Timer implements Runnable
    {

        @Override
        public void run() {
    
        while(true) 
        {
            try {
                Calendar cal = new GregorianCalendar();
                int hr = cal.get(Calendar.HOUR);
                int min = cal.get(Calendar.MINUTE);
                int sec = cal.get(Calendar.SECOND);
                timeLabel.setText(hr + ":" + min + ":" + sec);
                
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(SimpleAppFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList destinationList;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JTextField itemTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton moveButton;
    private javax.swing.JLabel simpleAppLabel;
    private javax.swing.JList sourceList;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
