<%-- 
    Document   : index
    Created on : Nov 3, 2016, 9:12:59 AM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
   <body data-track-group="Landing-Marquee">
       <div class="global-header mod-trello-blue mod-dark-background u-clearfix" data-track-group="Global Header">
           <div class="global-header-section mod-left"> <a class="global-header-section-logo" href="home.html">
                   <img alt="Home" class="global-header-section-logo-image" src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/trello-header-logos/af7af6ed478d3460709d715d9b3f74a4/trello-logo-white.svg"> </a> </div>
           <div class="global-header-section mod-right">   <a href="login823e.html?returnUrl=%2F" class="global-header-section-button">Log In</a> <a href="signup823e.html?returnUrl=%2F" class="global-header-section-button mod-primary">Sign Up</a>  </div> </div>
       <div class="layout-centered mod-white-text u-center-text header-section" data-track-prefix="Header Section"> <div class="layout-centered-content"> <h1>Trello lets you work more collaboratively and get more done.</h1>
               <p>Trello’s boards, lists, and cards enable you to organize and prioritize your projects in a fun, flexible and rewarding way. </p>  <a class="button mod-primary" href="signup.html" data-track="Sign Up"> Sign Up – It’s Free. </a>  </div>
           <div class="layout-centered-content"> <p class="small">Already use Trello? <a href="login.html" data-track="Login">Log in.</a> </p> </div>  </div>  <div class="board-container background-dark-bc mod-white-text u-center-text layout-centered">
               <div class="board-slider-wrap "> <div class="board active background-dark-bc"> <div class="layout-centered-content mod-white-text"> <p> The Design Team shares updates on current projects so everyone in the company knows what's going on. </p> </div>
                       <picture> <source media="(min-width: 800px)" srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/07ced7d72fcf302f25981df3d6fdb46f/usecases-board01.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/371849cc490bb134403a163247624663/usecases-board01@2x.jpg 2x">
                               <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/f0455b0e7cbf32e0c66a5464ab6bc052/usecases-mobile-board01.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/716ab6d6713bc62480c772ee5f984b73/usecases-mobile-board01@2x.jpg 2x">
                                   <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/07ced7d72fcf302f25981df3d6fdb46f/usecases-board01.jpg" alt="Company Overview: Keep track of all your team's moving pieces."> </picture> </div>
                   <div class="board background-dark-bc"> <div class="layout-centered-content mod-white-text"> <p> Onboarding new employees is easy for the People Team since they share orientation details directly on a Trello board. </p> </div>
                       <picture> <source media="(min-width: 800px)" srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/bb311e4d3417ac027a5e4545146389e7/usecases-board02.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/1d1ff7013d09ac8d10790740ed43e73c/usecases-board02@2x.jpg 2x">
                               <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/855f5c9ed12d3142f3f4e9622d5c5c83/usecases-mobile-board02.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/d9bf2e4bf32470ec7b4b4c3393fb6d00/usecases-mobile-board02@2x.jpg 2x">
                                   <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/bb311e4d3417ac027a5e4545146389e7/usecases-board02.jpg" alt="New Hire Onboarding: The easy way to handle all the logistics of an employee's first week."> </picture> </div>
                   <div class="board background-dark-bc"> <div class="layout-centered-content mod-white-text"> <p>The Marketing Team moves blog content through the editorial calendar all the way from "Writing" to "Published." </p> </div>
                       <picture> <source media="(min-width: 800px)" srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/3dedd89dc746f5bd94a7a1f089bf7a52/usecases-board03.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/ec1dbefb739b6aea9ef242f2207ab6b3/usecases-board03@2x.jpg 2x">
                               <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/16029109e0883bdd9aa4d4f972983940/usecases-mobile-board03.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/a3096e88713d7a34a404628882be9537/usecases-mobile-board03@2x.jpg 2x">
                                   <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/3dedd89dc746f5bd94a7a1f089bf7a52/usecases-board03.jpg" alt="Editorial Calendar: Organize and schedule content in advance."> </picture>
                   </div> <div class="board background-dark-bc"> <div class="layout-centered-content mod-white-text"> <p> The Sales Team updates the status of leads directly in the sales pipeline for all to see. </p> </div>
                       <picture> <source media="(min-width: 800px)" srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/6d087541e5e4a72bb33f0d7f6aa0f2e3/usecases-board04.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/13fc70e0f97124b5107d9c5b0df6b9b9/usecases-board04@2x.jpg 2x">
                               <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/019c7c526fe5d2c2492621d6d6bdc4a4/usecases-mobile-board04.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/d5ad7e0b3be63308a151af24810fad24/usecases-mobile-board04@2x.jpg 2x">
                                   <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/6d087541e5e4a72bb33f0d7f6aa0f2e3/usecases-board04.jpg" alt="Sales Pipeline: Nurture sales leads into done deals."> </picture> </div>
                   <div class="board background-dark-bc"> <div class="layout-centered-content mod-white-text"> <p> Since the Product Roadmap is on a Trello board, the Product team can focus on building rather than endless status update meetings. </p> </div>
                       <picture> <source media="(min-width: 800px)" srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/b7d066066af22a33d580843793e75ad1/usecases-board05.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/a337517350dfaae92a24a2845543f36f/usecases-board05@2x.jpg 2x">
                               <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/02dacfad76b7441638c8e383f8f5ece5/usecases-mobile-board05.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/2ce6e8106c2534527ef0ad32252f3645/usecases-mobile-board05@2x.jpg 2x">
                                   <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/b7d066066af22a33d580843793e75ad1/usecases-board05.jpg" alt="Product Development: A visual roadmap of all your team's tasks."> </picture> </div> </div>
               <div class="board-overlay background-dark-bc"> <div class="layout-centered-content mod-white-text u-center-text"> <p>From startups to Fortune 500 companies, Trello is the most visual way for teams to collaborate on any project. </p>  <a class="button mod-primary" href="signup.html" data-track="Sign Up"> Create Your Board </a>   </div> </div> </div>
           <div class="card-detail layout-centered mod-white-text u-center-text background-orange-sun"> <div class="layout-centered-content" style="max-width: 630px;"> <h2>Information At A Glance</h2> <p>Dive into the details by adding comments, attachments, and more directly to Trello cards. Collaborate on projects from beginning to end. </p> </div>
               <picture> <source media="(min-width: 800px)" srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/1b9100e29afb7df3e805a6c5210a202e/usecases-card.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/85e11d72fa12a14752e0d5a794dbc4e6/usecases-card@2x.jpg 2x">
                       <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/1c8ff82a1f9856939f9145f12b7096ed/usecases-mobile-card.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/5890fe14d9bbe1cf573bfd41c08bf0c0/usecases-mobile-card@2x.jpg 2x">
                           <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/1b9100e29afb7df3e805a6c5210a202e/usecases-card.jpg" alt="Add members and labels to card, and any other details or visuals you need."> </picture> </div>
           <div class="dream-teams layout-two-up mod-image-right mod-white-text background-red"> <div class="layout-two-up-content"> <div class="layout-two-up-content-text" style="order:1; -webkit:order: 1;"> <h2>Work With Any Team</h2> <p>Whether it’s for work, a side project or even the next family vacation, Trello helps your team stay organized.</p> </div>
                   <div class="layout-two-up-content-image" style="order:2; -webkit:order: 2;"> <picture> <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/43e915441342077c5fdc6be43b9c1c86/usecases-tiles.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/324f6acb50060a233256fa00e295529f/usecases-tiles@2x.jpg 2x">
                               <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/43e915441342077c5fdc6be43b9c1c86/usecases-tiles.jpg" width="846" alt="Create boards for all the teams in your life - at work, at home, and everything in between."> </picture> </div> </div> </div>
           <div class="power-ups background-light-purple layout-two-up mod-white-text "> <div class="layout-two-up-content"> <div class="layout-two-up-content-text"> <h2>A Productivity Platform</h2> <p>Integrate the apps your team already uses directly into your workflow. Power-Ups turn Trello boards into living applications to meet your team's unique business needs.</p>
                       <a href="power-ups.html" class="button mod-transparent mod-dark-background"> Power-Up Your Workflow </a> </div> <div class="layout-two-up-content-image u-center-text"> <picture>
                               <source srcset="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/b45c8bccde359af6cf2369ddb126ad4f/usecases-powerups.jpg 1x, https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/e3f3424afa9c7962cb566fef2b6e41da/usecases-powerups@2x.jpg 2x">
                                   <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/b45c8bccde359af6cf2369ddb126ad4f/usecases-powerups.jpg" width="580" alt="Trello integrates with apps you already love to use: Slack, Github, Evernote, Google Drive, and much more."> </picture> </div> </div> </div>
           <div class="background-sky mobile layout-two-up mod-white-text"> <div class="layout-two-up-content"> <div class="layout-two-up-content-text" style="order:1; -webkit:order: 1;"> <h2>Always In Sync</h2> <p>No matter where you are, Trello stays in sync across all of your devices. Collaborate with your team anywhere, from sitting on the bus to sitting on the beach.</p>
                       <a href="https://itunes.apple.com/app/trello-organize-anything/id461504587" data-track="iOS Badge" ><img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/0c89bea1f934eadd07d8284fead760d6/btn-appstore.png" width="159" alt="Download on the App Store"/></a> &nbsp;
                       <a href="https://play.google.com/store/apps/details?id=com.trello" data-track="Android"><img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/2d8bf64328f6c2666c1d5a3558fd7042/btn-playstore.png" width="169" alt="Download on Google Play"/></a> </div>
                   <div class="layout-two-up-content-image u-center-text" style="order:2; -webkit:order: 2;"> <div class="taco-img-wrap"> <img src="../d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/60dc711cb04607c6a8a0c55b045aeb6d/usecases-taco.jpg" alt="Meet Taco, our spokes-husky!"/> </div> </div> </div> </div>
           <div class="layout-centered mod-white-text u-center-text background-business-blue"> <img class="bc-logo" src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/730e47effc2c931d3b9a1d3f23818899/business-class-logo-white.svg" width="250"/> <div class="u-center-text layout-company-logos">
                   <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/dcf4dc3fb2aa61de5911cd7e881c0e7e/freshdirect.svg" alt="FreshDirect"> <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/20f39168f8235b4d8c461d796433e771/53.svg" alt="53">
                   <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/6f0a4ac4c16a8eaf8651ee915785997d/theverge.svg" alt="The Verge"> <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/20e7a157f944d3dfb0c982df4eba1df0/adobe.svg" alt="Adobe">
                   <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/4b97a98cd48dc6b77162e806f27e4c0c/pixar.svg" alt="Pixar"> <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/f5a25f44460d99e8a91086b98f194570/google.svg" alt="Google">
                   <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/22a18f54b643fd006a6ccb7ff85ed5ad/paypal.svg" alt="PayPal"> <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/7bdcee736843561e6c1026fe576255dd/kickstarter.svg" alt="Kickstarter">
                   <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/d5978c3278d66a6d651ac10af0498c7b/iconair.svg" alt="ICON Aircraft"> <img src="https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/company-logos/56b2cbd3496f4a32c17d3470e3a0e742/natgeo.svg" alt="ICON Aircraft"> </div>
               <div class="layout-centered-content"> <p>Companies of all shapes and sizes use Trello Business Class. Learn how Trello helps your team <b>work smarter</b>.</p> <a href="business-class.html" class="button mod-transparent mod-dark-background"> Work Smarter &rarr; </a> </div> </div>  <div class="layout-centered u-center-text">
                   <div class="layout-centered-content"> <p>What are you waiting for?<br/> <b>Sign up for free</b> and become one of the millions of people around the world who have fallen in love with Trello. </p>  <a class="button mod-primary" href="signup.html" data-track="Sign Up "> Sign Up – It’s Free. </a>  </div>   <div class="layout-centered-content">
                       <p class="small">Already use Trello? <a href="login.html" data-track="Login">Log in.</a> </p> </div>  </div>     <footer class="quiet" data-track-group="Footer"> <ul> <li><a href="tour.html">Tour</a></li> <li><a href="pricing.html">Pricing</a></li> <li><a href="platforms.html">Apps</a></li> <li><a href="jobs.html">Jobs</a></li> <li>
               <a target="_blank" href="http://blog.trello.com/">Blog</a></li> <li><a href="http://developers.trello.com/">Developers</a></li> <li><a href="about.html">About</a></li> <li><a href="http://help.trello.com/">Help</a></li> <li><a href="legal.html">Legal</a></li> </ul>
       <p> © Copyright 2016, Trello, Inc. All rights reserved. </p> </footer>  
    </body>
</html>
